name: test workflow

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install Dependencies
        run: |
          yarn install

      - name: Update PR status
        uses: actions/github-script@v6
        with:
          script: |
            const { pr_repo, pr_number } = context.payload.client_payload;
            github.rest.issues.createComment({
              owner: pr_repo.owner,
              repo: pr_repo.repo,
              issue_number: pr_number,
              body: 'E2E tests completed successfully'
            });
